# Disabled intentionally
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/simple_form.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'spec/**/*'
    - Gemfile
    - Guardfile
    - Vagrantfile

LineLength:
  Enabled: false # stupid spec, It's the 21st Century and wide-screen monitors
