default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3


# # Postgres
# &default: &default
#   adapter: postgresql
#   encoding: utf8
#   pool: 25
#   # port: 5432
#   prepared_statements: true
#   template: template1
#   timeout: 5000
#
# development:
#   <<: *default
#   database: githubby_development
#
# test:
#   <<: *default
#   database: githubby_test
#
# production:
#   <<: *default
#   database: githubby_production
